Repository 67P/kredits-contracts, pull requests merged in 2019-04, with the labels that each got.

#63 Fix contributor oracle permission auth
  apps/contributor/contracts/Contributor.sol
  contracts/KreditsKit.sol
Labels: in progress, kredits-2

#65 Use namehash from ethers.utils
  lib/contracts/kernel.js
  package-lock.json
  package.json
  scripts/deploy-kit.js
Labels: in progress, kredits-1

#66 Allow seed tx to fail
  config/seeds.js
  scripts/seeds.js
Labels: in progress, kredits-1

#67 Add balance when loading contributor
  apps/contributor/contracts/Contributor.sol
  lib/abis/Contributor.json
  scripts/list-contributors.js
Labels: in progress

#68 Update ipfs package
  lib/utils/ipfs.js
  package-lock.json
  package.json
Labels: in progress, kredits-1

#69 Fix permissions to manage contributors
  contracts/KreditsKit.sol
Labels: in progress

#70 Update seeds
  config/seeds.js
Labels: in progress

#74 Add some helpers to reset a fresh DAO and upgrade an app
  README.md
  package.json
  scripts/deploy-apps.sh
  scripts/every-app.sh
  scripts/upgrade.sh
Labels: kredits-1

#73 Convert contribution owner to ID, use smaller number formats
  apps/contribution/contracts/Contribution.sol
  apps/contributor/contracts/Contributor.sol
  apps/proposal/contracts/Proposal.sol
  apps/token/contracts/Token.sol
  config/seeds.js
  lib/abis/Contribution.json
  lib/abis/Contributor.json
  lib/abis/Proposal.json
  lib/abis/Token.json
  lib/contracts/contribution.js
  lib/contracts/contributor.js
  lib/contracts/proposal.js
  scripts/add-contribution.js
  scripts/list-contributions.js
  scripts/list-proposals.js
  scripts/seeds.js
Labels: kredits-2

#80 Rename ipfsHash to hashDigest in Contributor
  apps/contributor/contracts/Contributor.sol
  lib/abis/Contributor.json
  lib/contracts/contributor.js
Labels: kredits-1

#82 Improve list-contributions script
  scripts/list-contributions.js
Labels: kredits-1

#85 Fix contributor ID in seeds
  config/seeds.js
Labels: kredits-1

#86 Don't run `npm install` on bootstrap
  package.json
Labels: kredits-1

#87 Rename postinstall script
  README.md
  package.json
Labels: kredits-1

#92 Validate contribution docs against schema
  lib/contracts/contribution.js
  lib/serializers/contribution.js
  package-lock.json
  package.json
  scripts/add-contribution.js
Labels: kredits-2

#93 Production release to rinkeby
  README.md
  deployments/rinkeby/contribution.md
  deployments/rinkeby/contributor.md
  deployments/rinkeby/dao.md
  deployments/rinkeby/proposal.md
  deployments/rinkeby/token.md
  lib/addresses/KreditsKit.json
  lib/addresses/dao.json
Labels: kredits-1

#102 Add yarn lock files
  .gitignore
  apps/contribution/yarn.lock
  apps/contributor/yarn.lock
  apps/proposal/yarn.lock
  apps/token/yarn.lock
  yarn.lock
Labels: kredits-1

#96 Add pagination for .all methods
  lib/contracts/contribution.js
  lib/contracts/contributor.js
  lib/contracts/proposal.js
  lib/contracts/record.js
  lib/kredits.js
  lib/utils/pagination.js
  package.json
Labels: kredits-2

#109 Handle errors in contributor list script
  scripts/list-contributors.js
Labels: kredits-1

#111 Add Contributor validation against JSON schema
  lib/contracts/contributor.js
  lib/serializers/contributor.js
  scripts/add-contributor.js
Labels: kredits-1

#110 Add contract calls for total contribution balances
  apps/contribution/contracts/Contribution.sol
  apps/contributor/contracts/Contributor.sol
  lib/abis/Contribution.json
  lib/abis/Contributor.json
  scripts/list-contributions.js
  scripts/list-contributors.js
Labels: kredits-2

#114 Improve/fix scripts
  scripts/list-contributions.js
  scripts/list-contributors.js
Labels: kredits-1

#113 Add Gitea site/username to serializer and seeds
  config/seeds.js
  lib/serializers/contributor.js
Labels: kredits-1

#108 Add kredits-formatter and additionally format balance
  lib/contracts/contributor.js
  lib/utils/format-kredits.js
  scripts/list-contributors.js
Labels: kredits-1

#116 Release/deployment notes for latest contract updates on Rinkeby
  deployments/rinkeby/contribution.md
  deployments/rinkeby/contributor.md
  deployments/rinkeby/dao.md
Labels: kredits-1

#97 Add linter and travis.yml
  .eslintrc.js
  .solhint.json
  .travis.yml
  apps/.eslintrc.js
  apps/contribution/test/app.js
  apps/contributor/test/app.js
  apps/proposal/test/app.js
  apps/token/test/app.js
  lib/contracts/acl.js
  lib/contracts/base.js
  lib/contracts/contribution.js
  lib/contracts/contributor.js
  lib/contracts/index.js
  lib/contracts/kernel.js
  lib/contracts/proposal.js
  lib/contracts/record.js
  lib/kredits.js
  lib/serializers/contribution.js
  lib/serializers/contributor.js
  lib/utils/deprecate.js
  lib/utils/format-kredits.js
  lib/utils/ipfs.js
  lib/utils/pagination.js
  lib/utils/preflight.js
  lib/utils/validator.js
  package-lock.json
  package.json
  yarn.lock
Labels: kredits-2

#119 Fix apps lookup
  scripts/deploy-kit.js
Labels: kredits-1

#120 Fix canPerform method
  apps/contributor/contracts/Contributor.sol
Labels: kredits-1
