Repository 67P/kredits-contracts, pull requests merged in 2019-06, with the labels that each got.

#129 Add pre-commit hook and setup script
  package.json
  scripts/git-hooks/install
  scripts/git-hooks/pre-commit
Labels: kredits-1

#130 Add JS wrapper for Kit contract
  contracts/KreditsKit.sol
  lib/abis/KreditsKit.json
  lib/contracts/base.js
  lib/kreditskit.js
  scripts/new-dao.js
Labels: kredits-1

#121 Improve totalKreditsEarned
  apps/contribution/contracts/Contribution.sol
  apps/contributor/contracts/Contributor.sol
  lib/abis/Contribution.json
  lib/abis/Contributor.json
Labels: kredits-1

#133 Print total unconfirmed and confirmed contribution kredits
  scripts/list-contributions.js
Labels: kredits-1

#134 Update dependencies
  .travis.yml
  package-lock.json
  package.json
Labels: kredits-1

#135 Expose available network IDs
  lib/kredits.js
Labels: kredits-1

#138 Various small seed/script improvements
  .eslintignore
  config/seeds.js
  scripts/seeds.js
Labels: kredits-1

#142 Chore/update dependencies 2
  .travis.yml
  apps/contribution/arapp.json
  apps/contribution/artifact.json
  apps/contribution/code.sol
  apps/contribution/package-lock.json
  apps/contribution/package.json
  apps/contributor/arapp.json
  apps/contributor/package-lock.json
  apps/contributor/package.json
  apps/proposal/arapp.json
  apps/proposal/package-lock.json
  apps/proposal/package.json
  apps/token/arapp.json
  apps/token/package-lock.json
  apps/token/package.json
  arapp.json
  lib/contracts/kernel.js
  package-lock.json
  package.json
  scripts/fix-package-lock.js
  scripts/seeds.js
Labels: kredits-2

#141 Test setup
  apps/contribution/package-lock.json
  apps/contribution/package.json
  apps/contributor/package-lock.json
  apps/contributor/package.json
  apps/proposal/package-lock.json
  apps/proposal/package.json
  apps/token/package-lock.json
  apps/token/package.json
  package-lock.json
  package.json
Labels: kredits-3
